### ISSUE TITLE
Xen / Netfront support

### ISSUE THREAD

**Issue by crowdwave** [Solo5/solo5#134]
I'd like to run Solo5 on Xen based clouds such as EC2 and Rackspace.

It would be good if I could do that with Solo5/MirageOS, so requesting driver support.

thanks!

**Comment by mato** [comment]
There are no plans to add support for the Xen platform to Solo5.

The amount of effort would be significant and IMO better spent on adding HVM support to the existing Mirage `xen` target based on Mini-OS. I believe that upstream (Xen) Mini-OS has had some work done on it to support HVM; if you'd like to see this happen in Mirage I suggest filing an issue on [mirage/mirage](https://github.com/mirage/mirage) or [mirage/mirage-platform](https://github.com/mirage/mirage-platform) so that it doesn't get forgotten.
