### ISSUE TITLE
[FreeBSD] [hvt] hw.vmm.destroy fails with "Operation not permitted"

### ISSUE THREAD

**Issue by mato** [Solo5/solo5#312]
Since this change, the "cleaning up /dev/vmm/solo5-PID" step does no longer work (installed via `atexit(cleanup_vm)` and `atexit(cleanup_vmfd)` in `hvt_freebsd.c`), since `sysctlbyname("hw.vmm.destroy", ...` receives a permission denied (not output anywhere, see ktrace/kdump below).

I'm not sure what the best way to handle this is... given that `solo5-hvt` indeed created the device (via `hw.vmm.create`), it should be responsible for cleaning up. but in the meantime it lost sufficient privileges to clean it up. Any thoughts? The `vmfd` is no critical AFAICT since unix cleans up all open file descriptors when a process exits. ~~A solution would be to chown `/dev/vmm/solo5-PID` to nobody to enable the dropped priv user to destroy that device.~~

```bash
  7753 solo5-hvt CALL  write(0x1,0x820dffe10,0x1c)
  7753 solo5-hvt GIO   fd 1 wrote 28 bytes
       "Solo5: solo5_exit(0) called
       "
  7753 solo5-hvt RET   write 28/0x1c
  7753 solo5-hvt CALL  ioctl(0x3,0xc0907601,0x800644010)
  7753 solo5-hvt RET   ioctl 0
  7753 solo5-hvt CALL  close(0x3)
  7753 solo5-hvt RET   close 0
  7753 solo5-hvt CALL  __sysctl(0x7fffffffe330,0x2,0x7fffffffe380,0x7fffffffe378,0x2015fe,0xe)
  7753 solo5-hvt SCTL  "sysctl.name2oid"
  7753 solo5-hvt RET   __sysctl 0
  7753 solo5-hvt CALL  __sysctl(0x7fffffffe380,0x3,0,0,0x800649000,0xa)
  7753 solo5-hvt SCTL  "hw.vmm.destroy"
  7753 solo5-hvt RET   __sysctl -1 errno 1 Operation not permitted
```

_Originally posted by @hannesm in https://github.com/Solo5/solo5/pull/286#issuecomment-455878784_

**Comment by mato** [comment]
@hannesm Good catch. I'm not sure what to do about it as there's no way for the `sysctl()` to succeed if the caller is not root. This is an unfortunate design error in the FreeBSD `vmm` APIs.

Given that this will prevent a clean restart of `solo5-hvt` once in a while (due to the VM name possibly clashing with an earlier-used VM name, which did not get cleaned up due to this bug), and is probably also a resource leak, we should do something about it sooner rather than later.

What would you suggest? The only straightforward fix I can see for now which can be done quickly/backward compatibly seems to be to revert the privilege drop on hvt/FreeBSD entirely. In the longer-term I'd report a bug on the FreeBSD `vmm` side and see if we can convince them to accelerate the "Allow vmm use by non-root" use-case.

**Comment by hannesm** [comment]
First, I like dropping privileges. That FreeBSD VMM API is not very nice in this case, as `sysctl` requires root.
So, what do others do? If you run `bhyve` (the CLI) to start a VM, a `/dev/vmm/myvm` is created. But nobody cleans this up. So in a lot of deployment utilities (such as my shell scripts), you run `bhyvectl --vm=myvm --destroy` before the actual `bhyve` (`bhyve` complains if the `/dev/vmm/myvm` is already there and you try to start `myvm`). For solo5, we could do the same, i.e. do a `sysctl hw.vmm.destroy myvm` before the `hw.vmm.create` - would this work? I can't think of unintentional races, since `solo5` uses `solo5-$PID` as vm name (another discussion is whether this should be configurable by a command-line argument, then we could behave as the `bhyve` utility and exit early if `/dev/vmm/myvm` is present -- I I actually suspect `hw.vmm.create` will fail if the given name is already present -- confirmed, getting: `solo5-hvt.net: Cannot create VM 'solo5': File exists`).

What I do atm is to run `bhyvectl --vm=myvm --destroy` in my albatross supervisor once a VM quits (see https://github.com/hannesm/albatross/commit/943ea45e256badd57d039db61c153228974b58f7 if you're interested).

So, apart from adding documentation "this behaves similarly to other bhyve instances", and removing the (unused) `sysctl hw.vmm.destroy`, I wouldn't change much.

and yes, unfortunately it seems that there aren't many improvements in respect to the control interface or your `mprotect` suggestions on their side :/

**Comment by mato** [comment]
Ok, so, in the light of:

1. Discussion in #316, the real fix here is as described in https://github.com/Solo5/solo5/pull/316#issuecomment-464757104 (fixing the FreeBSD vmm APIs).
2. The build system refactoring in #326 changes the way hvt modules work, and the `HVT_DROP_PRIVILEGES=0` case will effectively be non-functional until I re-design that to not use compile-time flags. However, in the mean time, I need the tests to pass!

I'm going to make an executive decision here, which is: The FreeBSD privilege dropping introduced in #286 will be **reverted** on `master` shortly. 

Also, I'm going to close all issues/PRs related to this except #282, since the multiple discussions are confusing. We can discuss how to proceed forward there.

Note to self: **TODO**: The _existing_ VM cleanup code for FreeBSD and OpenBSD should be audited and at  `warn()` should be used in the atexit handler(s) if any syscalls fail.
/cc @sg2342 @hannesm
