### ISSUE TITLE
[spt] Need an executable heap for node

### ISSUE THREAD

**Issue by ricarkol** [Solo5/solo5#321]
Nodejs (rumprun) needs an executable heap for its JIT. The way around that was by cheating a bit and use "PROT_READ implies PROT_EXEC". But that's forbidden in spt (which is the right thing to do), so really don't know what to do. One option would be to add something like an optional EXTRA_MMAP_FLAG to solo5 to be used with care and a big warning.

**Comment by mato** [comment]
Right, since you need to run the node JIT, you need to get executable pages from somewhere. And you are correct, in the Solo5 design there is no way to get "more" executable pages after loading the unikernel, this is deliberate.

So, what to do? I can see two options:

1. A hack, which would be to provide a run-time option to the spt tender (and eventually maybe also hvt for consistency) to add `PROT_EXEC` to the `mmap()` call mapping guest memory. Unfortunately, this also means you will get an **executable stack**, as the stack is not separate from the heap. So you will lose quite a bit of your security posture.

2. Have you considered AOT compiling all your node.js code instead? There are projects around, such as https://github.com/lastmjs/node-compiler that claim to be able to compile any node.js application down to a single ELF executable. Obviously you'd have to port that to NetBSD/rumprun, but it is by far the better approach to running node.js code in a Solo5 type environment. (/cc @djwillia!)

**Comment by djwillia** [comment]
I don't know the answer to the question of what to do about JIT and it seems like it's a complicated thing.  It would be nice to be able to push everything to compile time, but I don't think we can do that for some use-cases that are otherwise a good fit for Solo5.  I would be in favor of doing the hack suggested in number 1 with a warning so that the rump-on-solo5 stuff (used by nabla containers) doesn't have to fork Solo5.

It sounds like an interesting longer-term project to think a bit more about in what cases you can get away without a JIT for things like node.JS...

**Comment by mato** [comment]
> It would be nice to be able to push everything to compile time, but I don't think we can do that for some use-cases that are otherwise a good fit for Solo5. 

Why not?

> I would be in favor of doing the hack suggested in number 1 with a warning so that the rump-on-solo5 stuff (used by nabla containers) doesn't have to fork Solo5.

In that case, please submit a PR for `spt` which adds a run-time option with a suitably dangerous name e.g. `--x-exec-heap` and prints the warning `Running with an executable guest heap and stack, security posture will be reduced.` at run time.

**Comment by ricarkol** [comment]
> Why not?
> 
> >
One of those use cases is openwhisk (serverless), where nodejs processes (also called stem cell containers) take new javascript code over http and then just evaluate (`eval()`) it directly on the same process.

> In that case, please submit a PR for `spt` which adds a run-time option with a suitably dangerous name > e.g. `--x-exec-heap` and prints the warning `Running with an executable guest heap and stack, security > posture will be reduced.` at run time.
>
> >
Will do, thanks for the suggestions.

Will be thinking of a proper fix for all of this, like rethinking the openwhisk model for unikernels.

**Comment by mato** [comment]
> take new javascript code over http and then just evaluate (eval()) it directly on the same process.

Oh.

Anyway, I've merged your PR. Please close this if happy.

> Will be thinking of a proper fix for all of this, like rethinking the openwhisk model for unikernels.

The recent thread on the mailing list about webassembly is relevant, read through the pointers there if you want some inspiration.

**Comment by ricarkol** [comment]
Happy with this, closing

**Comment by mato** [comment]
FWIW, I just remembered and this may be relevant to your interests: support for running V8 without a JIT was announced just recently: https://v8.dev/blog/jitless

Quoting from that announcement:

> But in some situations it can be desirable to run V8 without allocating executable memory:
>
>    Some platforms (e.g. iOS, smart TVs, game consoles) prohibit write access to executable memory for non-privileged applications, and it has thus been impossible to use V8 there so far; and
    disallowing writes to executable memory reduces the attack surface of the application for exploits.

In other words, running in an environment such as Solo5 is exactly this kind of use-case.
