### ISSUE TITLE
solo5_yield()/HVT_HYPERCALL_POLL hangs on Linux if deadline has passed

### ISSUE THREAD

**Issue by hannesm** [Solo5/solo5#460]
While pairing with @Reperator yesterday, we discovered some inconvenience in respect to yield. On Linux with hvt, a tiny sleep on the MirageOS side never returns. This behaviour is different on FreeBSD. EDIT: The behaviour on spt aligns with the expected one (the timerfd uses `SYS_TFD_TIMER_ASTIME`).

An example unikernel (copied hello, adapted the sleep to 0 nanoseconds)

config.ml:
```OCaml
open Mirage
let main = foreign "Unikernel.Hello" (time @-> job)
let () = register "hello" [main $ default_time]
```

unikernel.ml:
```OCaml
open Lwt.Infix
module Hello (Time : Mirage_time.S) = struct
  let start _time =
    let rec loop = function
      | 0 -> Lwt.return_unit
      | n ->
        Logs.info (fun f -> f "hello");
        Time.sleep_ns 0L >>= fun () ->
        loop (n-1)
    in
    loop 4
end
```

expected behaviour (observed on FreeBSD with hvt):
```bash
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Bindings version v0.6.4
Solo5: Memory map: 512 MB addressable:
Solo5:   reserved @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x1d7fff)
Solo5:     rodata @ (0x1d8000 - 0x203fff)
Solo5:       data @ (0x204000 - 0x2a2fff)
Solo5:       heap >= 0x2a3000 < stack < 0x20000000
2020-05-12 09:06:39 -00:00: INF [application] hello
2020-05-12 09:06:39 -00:00: INF [application] hello
2020-05-12 09:06:39 -00:00: INF [application] hello
2020-05-12 09:06:39 -00:00: INF [application] hello
Solo5: solo5_exit(0) called
```

observed behaviour on Linux:
```bash
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Bindings version v0.6.4
Solo5: Memory map: 512 MB addressable:
Solo5:   reserved @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x1cffff)
Solo5:     rodata @ (0x1d0000 - 0x201fff)
Solo5:       data @ (0x202000 - 0x296fff)
Solo5:       heap >= 0x297000 < stack < 0x20000000
2020-05-12 09:08:55 -00:00: INF [application] hello
..and now it waits (indefinitely? - at least more than 10 seconds)..
```

**Comment by hannesm** [comment]
experimental evidence shows that using a sleep of `100000L` ns on Linux is to get the intended behaviour.

from `timer_settime(2)` .. `a value of 0 disarms the timer`. In yield.c there's `if (deadline <= now) t.timeout_nsecs = 0`. I'd suggest to check in hvt_core.c in `hypercall_poll` in the `#if defined(__linux__)` branch whether the t.timeout_nsecs is 0, and if so, not add the timerfd to the wait set. Now I've no clue what the semantics of epoll are if the waitsetfd is empty (maybe that needs to be checked as well).

**Comment by hannesm** [comment]
on a separate note, i was slightly confused that an absolute time is passed down from mirage-solo5, is there a specific reason for this? it may be worth to change to a relative duration (breaks API, but only between solo5-bindings-* and mirage-solo5).

**Comment by mato** [comment]
Confirmed, thanks for the test case. Looking into it.

**Comment by mato** [comment]
@hannesm:

How about this:

```diff
--- a/tenders/hvt/hvt_core.c
+++ b/tenders/hvt/hvt_core.c
@@ -224,6 +224,7 @@ static void hypercall_poll(struct hvt *hvt, hvt_gpa_t gpa)
             .tv_nsec = t->timeout_nsecs % 1000000000ULL
         }
     };
+    it.it_value.tv_nsec |= 1;
     if (timerfd_settime(timerfd, 0, &it, NULL) == -1)
         err(1, "timerfd_settime() failed");
     /*

```

Given that +- one nanosecond of precision seems irrelevant in the context of a sleep performed by a moderately expensive hypercall, this feels like the simplest and cheapest way, in terms of instructions executed, to ensure that `it.it_value` is always non-zero.

> experimental evidence shows that using a sleep of 100000L ns on Linux is to get the intended behaviour.

I don't follow. What "intended behaviour" are you referring to here?

> on a separate note, i was slightly confused that an absolute time is passed down from mirage-solo5, is there a specific reason for this? it may be worth to change to a relative duration (breaks API, but only between solo5-bindings-* and mirage-solo5).

I don't follow this either, sorry.

There are two APIs involved:

1. The guest-side Solo5 public API `solo5_yield(solo5_time_t deadline, solo5_handle_set_t *ready_set)` uses the absolute value, as seen by the guest's monotonic clock (`solo5_clock_monotonic()`).
2. The internal hvt tender/bindings API and ABI for `HVT_HYPERCALL_POLL` uses a relative `uint64_t timeout_nsecs`.

What would you like explained and/or changed?

**Comment by hannesm** [comment]
> Given that +- one nanosecond of precision seems irrelevant in the context of a sleep performed by a moderately expensive hypercall, this feels like the simplest and cheapest way, in terms of instructions executed, to ensure that it.it_value is always non-zero.

fine with me.

> > experimental evidence shows that using a sleep of 100000L ns on Linux is to get the intended behaviour.
>
> I don't follow. What "intended behaviour" are you referring to here?

intended is "sleep does sleep for x ns, not forever". Rephrased above is "When sleeping < 100000L ns in OCaml, the unikernel gets stuck".

> The guest-side Solo5 public API `solo5_yield(solo5_time_t deadline, solo5_handle_set_t *ready_set)` uses the absolute value, as seen by the guest's monotonic clock.

I am curious why this is as it is at the moment. The alternative would be `solo5_yield(solo5_time_t sleep_duration, solo5_handle_set_t *ready_set)`.

**Comment by mato** [comment]
> intended is "sleep does sleep for x ns, not forever". Rephrased above is "When sleeping < 100000L ns in OCaml, the unikernel gets stuck".

Ah, so what you're saying is that the _cost_ of a sleep from OCaml is on the order of 100000 ns, since lower sleeps result in missing the deadline and a hang, due to this bug. There's not much we can do about the cost of short sleeps -- @Reperator, do you expect to need exact short sleeps of < 100000 ns for your hardware driver work?

In any case, my suggested change will ensure that things no longer hang, but you'll always "sleep" for at least whatever the cost of the sleep getting through all the layers and back is, likely more than 100000 ns, hardware/CPU-generation/bindings dependent.

> I am curious why this is as it is at the moment. The alternative would be solo5_yield(solo5_time_t sleep_duration, solo5_handle_set_t *ready_set).

See this https://github.com/Solo5/solo5/pull/201#discussion_r122984006 from 2017. Absolute vs. relative timeouts in APIs is a popular operating systems bikeshed, I deliberately picked the former when designing the public API, unlikely to change now.

**Comment by mato** [comment]
> whatever the overhead of the sleep getting through all the layers and back is, likely more than 100000 ns, hardware/CPU-generation/bindings dependent.

I benchmarked this a bit, using the improved `test_time` in #462. **For the C layers only** on 5th-generation Intel hardware this varies between 30k-80k ns depending on system load. `spt` is less, but not much, around 20k-40k ns. In any case, the resolution of the actual clock on Linux appears to be on the order of 100k ns, i.e. sleeping for less than that will get you around that number (assuming the deadline has not passed due to overheads).

**Comment by hannesm** [comment]
thanks @mato for your further investigation and proposed fix

**Comment by Reperator** [comment]
> @Reperator, do you expect to need exact short sleeps of < 100000 ns for your hardware driver work?

I don't, I just need my unikernel to not hang. We came across the problem because we were playing around with the main loop of mirage-solo5. My driver was performing badly on hvt due to mirage-solo5 calling `solo5_yield()` even though my driver was ready to run. We wrote [a small workaround](https://github.com/Reperator/mirage-solo5/commit/5cf309ea602ca2a4796935c3c2ef6bf2ff23986b) to detect poll mode drivers and skip calling `solo5_yield()` if no threads are waiting for work on a handle.
